// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxjgfpwkazgquxxbyzwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4amdmcHdrYXpncXV4eGJ5endnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MTE3MjMsImV4cCI6MjA2MjI4NzcyM30.etv8by2XUzZjJ6Xn8n_ZJrGEjxwQFT1tmZVPQN7G-Kg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);